name: SLSA on Windows

on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
    steps:
      - run: |
          git config --global core.eol lf
          git config --global core.autocrlf input
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: cp README.md release_artifact_windows
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: release_artifact_windows
          name: release_artifact_windows
          if-no-files-found: error
      - id: hash
        run: |
          set -euo pipefail
          sha256sum -t release_artifact_windows > checksum
          echo "hash=$(cat checksum | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.build.outputs.hash }}"
      upload-assets: true # NOTE: This does nothing unless 'upload-tag-name' parameter is also set to an existing tag
